server:
  port: 8082
spring:
  kafka:
    enabled: false
    broker-list: localhost:9092
    producer:
      group-id: test-producer-group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
   # schema: classpath:static/sql/message.sql
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        min-idle: 0
        max-active: 8
  mqtt:
    enabled: 1

mq:
  message:
    topic: message-push

mqtt:
  server:
    uri: tcp://localhost:61613
    username: admin
    password: password
    clientId: producer-01
    timeout: 10
    keepAliveInterval: 10
    cleanSession: true
    qos: 2
    retained: false

